# basic
name: myfirstflutterapp
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.0+1

# environment
environment:
  sdk: '>=3.4.3 <4.0.0'

# dependencies
dependencies:
  flutter:
    sdk: flutter
  # flutter_icons: ^1.0.0

# dev_dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# flutter
flutter:
  uses-material-design: true
  assets:
    - assets/img/common/
    - assets/fonts/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/PretendardVariable.ttf
